FROM devops/employee-microservice-node:latest

WORKDIR /var/opt/employee-microservice-node
# Add source files
COPY . .

ENV PORT 8000
EXPOSE 8000

# Silent start because we want to have our log format as the first log
CMD ["npm", "start", "-s"]
